version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    networks:
      - ainszon
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=Ainszon
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379" # Expose Redis port
    # environment:
    #   - REDIS_PASSWORD=your_password # Set the Redis password
    # command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"] # Require password authentication
    networks:
      - ainszon

networks:
  ainszon:
    driver: bridge
